name: autoencoder
dependencies:
  - numpy
  - pandas
  - tensorflow
  - scikit-learn
  - requests
  - pyyaml
  - python-dotenv
  - joblib
  - seaborn
  - pip:
      - prometheus-api-client
      - prometheus_client